source 'http://rubygems.org'

gem 'compass', '~>1.0.0.alpha.21'
gem 'toolkit', '~>2.3'
gem 'breakpoint', '~>2.4'
gem 'singularitygs', '~> 1.2.1'
gem 'rb-fsevent', '~> 0.9'
gem 'singularity-extras', '<1.0.0'
