<?php

/**
 * Helper function to add module directory to theme registry.
 *
 * From http://www.metachunk.com/blog/adding-module-path-drupal-7-theme-registry
*/

function borealis_theme_registry_write(&$theme_registry, $mod_path) {
  $theme_registry_copy = $theme_registry;       // munge on a copy
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $mod_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('node');
  foreach ($hooks as $h) {
    _borealis_insert_after_first_element($theme_registry[$h]['theme paths'], $mod_path);
  }
}

/**
 * Helper function for re-ordering arrays (needed by theme_registry_alter)
 *
 * From http://www.metachunk.com/blog/adding-module-path-drupal-7-theme-registry
*/
function _borealis_insert_after_first_element(&$a, $element) {
  if(is_array($a)) {
    $first_element = array_shift($a);
    array_unshift($a, $first_element, $element);
  }
}

/**
 * Helper function to retrieve a block and add it to the give render array
 */
function borealis_render_array_block(&$render_array, $module, $delta) {
  $block = block_load($module, $delta);
  $block = _block_get_renderable_array(_block_render_blocks(array($block)));
  array_push($render_array, $block);
}

/**
  * Helper function for saving settings to a variable
  */
function borealis_ajax_settings_save($form, $form_state) {
  $key = $form['borealis_key']['#value'];
  $trigger = $form_state['triggering_element']['#name'];
  $value = $form_state['triggering_element']['#value'];
  variable_set($key . '_' . $trigger, $value);
}