# Pull gems from RubyGems
source 'https://rubygems.org'

gem 'compass', '~>1.0.0.alpha.21'

gem 'toolkit', '~>2.3'
gem 'breakpoint', '~>2.4'
gem 'singularitygs', '~> 1.2.1'
gem 'singularity-extras', '>=0.0.3'
gem 'color-schemer', '>=0.2.3'
gem 'modular-scale', '>=1.0.6'
gem 'sassy-buttons', '>=0.1.4'

group :development do
  gem 'guard-livereload'
  gem 'yajl-ruby'
  gem 'rb-fsevent'
  gem 'guard-compass'
end
