---
# The main playbook to deploy the site

- name: "Server setup tasks"
  hosts: 127.0.0.1
  connection: local
  sudo: yes
  roles:
   - common
   - web
   - ruby

- name: "Training specific tasks"
  hosts: 127.0.0.1
  connection: local
  roles:
   - training
