---
- name: restart apache
  action: service name=apache2 state=restarted

- name: restart nginx
  action: service name=nginx state=restarted

- name: restart php-fpm
  action: service name=php5-fpm state=restarted

- name: restart varnish
  action: service name=varnish state=restarted

