#!/bin/sh

echo " +----------------------------------------------------------------------------+"
echo " | Four Kitchens Training Server.                                             |"
echo " |                                                                            |"
echo " | Welcome to the Four Kitchens training server. This is a beta test to       |"
echo " | use during our trainings. It was made with love and care by the webchefs   |"
echo " | at Four Kitchens, starting with the amazing work of Amazee Labs.           |"
echo " |                                                                            |"
echo " | If you have any issues with your development server during training,       |"
echo " | please ask one of your trainers for help and support.                      |"
echo " |                                                                            |"
echo " | Run 'cd public_html' to get to this trainings files.                       |"
echo " |                                                                            |"
echo " +----------------------------------------------------------------------------+"
echo
