<?php

/**
 * Install hooks for the magic module.
 */


/**
 * Implements hook_install.
 */
function magic_install() {
  // TODO: Add in support to move Aurora settings automatically.

  db_update('system')
    ->fields(array('weight' => 200))
    ->condition('name', 'magic', '=')
    ->execute();

}

/**
 * Implements hook_schema.
 */
function magic_schema() {
  $schema['cache_magic'] = drupal_get_schema_unprocessed('system', 'cache');
  return $schema;
}
